#define HARDWARE_VERSION_121 010201
#define HARDWARE_VERSION_201 020001

#define HARDWARE_VERSION HARDWARE_VERSION_121

#define SAFE HIGH


#if HARDWARE_VERSION == HARDWARE_VERSION_121

#define HARDWARE_VERSION_STRING "1.2.1"
#define HARDWARE_VERSION_MAJOR 1
#define HARDWARE_VERSION_MINOR 2
#define HARDWARE_VERSION_PATCH 1

// MOTOR CONTROL
#define ON_B 0
#define FORWARD_MOTOR 6
#define BACKWARD_MOTOR 2
#define ON_A 4
#define CURRENT_SENSE 27

// LIMIT SWITCHES
#define CLOSE_LIMIT 8
#define OPEN_LIMIT 7

// INPUT BUTTONS
#define OPEN 10
#define TOGGLE_CLOSE 12
#define ABORT 9
#define TOGGLE_OPEN 13
#define CLOSE 11

// SAFETY_SENSORS
#define SAFE_TO_MOVE_1 14
#define SAFE_TO_MOVE_2 15

// INPUTS
#define MAX_SPEED 26

// OUTPUTS
#define BUZZER 22

#elif HARDWARE_VERSION == HARDWARE_VERSION_201

#define HARDWARE_VERSION_STRING "2.0.1"
#define HARDWARE_VERSION_MAJOR 2
#define HARDWARE_VERSION_MINOR 0
#define HARDWARE_VERSION_PATCH 1

// MOTOR CONTROL
#define ON_B 0
#define FORWARD_MOTOR 6
#define BACKWARD_MOTOR 2
#define ON_A 4
#define CURRENT_SENSE 27

// LIMIT SWITCHES
#define CLOSE_LIMIT 8
#define OPEN_LIMIT 7

// INPUT BUTTONS
#define OPEN 9
#define TOGGLE_CLOSE 11
#define ABORT 13
#define TOGGLE_OPEN 12
#define CLOSE 10

// SAFETY_SENSORS
#define SAFE_TO_MOVE_1 14
#define SAFE_TO_MOVE_2 15

// INPUTS
#define MAX_SPEED 26

// OUTPUTS
#define BUZZER 22

#endif
